# Generated by Django 4.0.6 on 2022-07-14 01:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='hours_slept',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='lines_written',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='new_people',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='pages_read',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='steps_taken',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='habit',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Habit_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('tracking_unit', models.IntegerField(default=0)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_trackers', to='habits.habit')),
            ],
        ),
    ]
